name: delete deploy preview

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  Get-Deploy-ID:
    runs-on: ubuntu-latest
    outputs:
      value: ${{ steps.get-value.outputs.DEPLOY_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install @actions/github @actions/core
      - name: Get value from comment
        id: get-value
        run: node .github/workflows/js/get-value.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Call-Api:
    runs-on: ubuntu-latest
    needs: Get-Deploy-ID
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Call API
        run: |
          echo "The value is ${{ needs.Get-Deploy-ID.outputs.value }}"
          netlify api deleteSiteDeploy --data "{\"deploy_id\": \"${{ needs.Get-Deploy-ID.outputs.value }}\", \"site_id\": \"${{ secrets.NETLIFY_SITE_ID }}\"}"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}